package com.ivor.ivormusic.data.youtube

// The web clients Koda calls InnerTube as, and what each must send. The
// native clients that resolve streams are in data/stream/PlayerClients.kt.

/**
 * The browser User-Agent sent wherever Koda speaks as a web client: InnerTube
 * on both hosts, NewPipe's downloader and the feed fetches. It has to be the
 * same everywhere, and plausible against [WEB_VERSION] and
 * [WEB_REMIX_VERSION]: a Chrome years older than the InnerTube build it claims
 * is self-inconsistent, which reads as synthetic traffic.
 */
internal const val BROWSER_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

/**
 * The public InnerTube key of the WEB client.
 *
 * NOTE TO REVIEWERS: this is not a secret. It is generated by Google and
 * embedded in the public JavaScript of YouTube and YouTube Music, and it is
 * the same key every open-source YouTube project uses (NewPipe Extractor,
 * yt-dlp, ytmusicapi, Invidious). It is rate-limited per address, not per
 * key, grants no access to private data and only names the client type, so
 * moving it to BuildConfig or the environment would protect nothing.
 *
 * Reference: https://github.com/AyMaN-GhOsT/YouTube-Internal-Clients
 */
internal const val INNER_TUBE_API_KEY = "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8"

// Current InnerTube client versions. YouTube rejects clients older than a few
// months (HTTP 400 on browse is the symptom); bump these together when
// refreshing. Re-derived from the bootstrap HTML of music.youtube.com and
// www.youtube.com in September 2026 (INNERTUBE_CLIENT_VERSION), and both
// confirmed live: WEB_REMIX answers a VL<playlistId> browse with a full
// musicPlaylistShelfRenderer, WEB answers /next.
internal const val WEB_REMIX_VERSION = "1.20260901.12.00"
internal const val WEB_VERSION = "2.20260903.01.00"
