package com.ivor.ivormusic.data

import org.junit.Assert.assertEquals
import org.junit.Test

class DownloadedCaptionStoreTest {

    private fun track(language: String, auto: Boolean = false) =
        CaptionTrack(languageCode = language, name = language, baseUrl = "https://example/$language", isAutoGenerated = auto)

    private fun preferred(
        available: List<CaptionTrack>,
        saved: String? = null,
        device: List<String> = emptyList(),
    ) = DownloadedCaptionStore.preferredTracks(available, saved, device)
        .map(DownloadedCaptionStore::keyOf)

    @Test
    fun `the saved language, the phone's and English are preferred, in listed order`() {
        val available = listOf(track("de"), track("en-GB"), track("fr"), track("hi"), track("ja"))
        assertEquals(
            listOf("en-GB", "fr", "hi"),
            preferred(available, saved = "fr-CA", device = listOf("hi"))
        )
    }

    @Test
    fun `an authored track beats the auto-generated one for the same language`() {
        val available = listOf(track("en"), track("en", auto = true), track("ko", auto = true))
        assertEquals(listOf("en"), preferred(available))
    }

    @Test
    fun `an auto-generated track is kept when it is the only one in a wanted language`() {
        val available = listOf(track("ja"), track("en", auto = true))
        assertEquals(listOf("en:auto"), preferred(available))
    }

    @Test
    fun `with no wanted language the first track is kept`() {
        val available = listOf(track("ja"), track("ko", auto = true))
        assertEquals(listOf("ja"), preferred(available, saved = "fr", device = listOf("de")))
    }

    @Test
    fun `no tracks means nothing to keep`() {
        assertEquals(emptyList<String>(), preferred(emptyList(), saved = "en"))
    }
}
