package com.ivor.ivormusic.data

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class DownloadedCaptionStoreTest {

    private fun track(language: String, auto: Boolean = false) =
        CaptionTrack(languageCode = language, name = language, baseUrl = "https://example/$language", isAutoGenerated = auto)

    @Test
    fun `a short list is kept whole and in order`() {
        val available = listOf(track("ja"), track("en"), track("ja", auto = true))
        assertEquals(
            available,
            DownloadedCaptionStore.tracksToKeep(available, savedLanguage = null, deviceLanguages = emptyList())
        )
    }

    @Test
    fun `a long list keeps the wanted languages and the spoken one within the limit`() {
        val languages = (1..40).map { "x$it" }
        val available = languages.map { track(it) } +
            listOf(track("hi"), track("en-GB"), track("fr"), track("ko", auto = true))

        val kept = DownloadedCaptionStore.tracksToKeep(
            available,
            savedLanguage = "fr-CA",
            deviceLanguages = listOf("hi"),
        )

        assertEquals(DownloadedCaptionStore.MAX_TRACKS_PER_VIDEO, kept.size)
        // Saved language first, then the phone's, then English, then the auto track.
        assertEquals(listOf("fr", "hi", "en-GB", "ko"), kept.take(4).map { it.languageCode })
        assertTrue(kept[3].isAutoGenerated)
        // The rest fill up in the order YouTube listed them.
        assertEquals(languages.take(8), kept.drop(4).map { it.languageCode })
    }
}
