package com.ivor.ivormusic.data

import android.content.Context
import com.ivor.ivormusic.util.KLog
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.util.Locale

/**
 * Caption files kept beside a downloaded video, so an offline watch still has
 * subtitles.
 *
 * A download used to be the picture and the sound and nothing else: the
 * captions menu reads YouTube's timedtext endpoint, so the moment there was no
 * connection - the reason anyone downloads - a video in another language had
 * no subtitles at all.
 *
 * Files rather than state. Each video gets a folder of raw WebVTT documents
 * and an index naming them; nothing is held in memory, so every reader sees
 * what is on disk and there is no instance to keep in step. They live in the
 * app's own storage, not next to the MP4: a public sidecar would need a second
 * MediaStore row per language and would be orphaned by any file manager that
 * moved the video.
 *
 * A saved track is handed out as an ordinary [CaptionTrack] whose [CaptionTrack.baseUrl]
 * is a `file:` address, so the captions menu and the saved-language restore
 * treat it like any other. Only the cue load has to know the difference, and
 * it asks [cues].
 */
internal class DownloadedCaptionStore(context: Context) {

    private val root = File(context.applicationContext.filesDir, DIRECTORY)

    private fun folder(videoId: String) = File(root, videoId.replace(UNSAFE, "_"))

    /** Write one track's WebVTT. A track already saved for this video is replaced. */
    fun save(videoId: String, track: CaptionTrack, vtt: String) {
        if (vtt.isBlank()) return
        try {
            val dir = folder(videoId).apply { mkdirs() }
            val fileName = buildString {
                append(track.languageCode.replace(UNSAFE, "_"))
                if (track.isAutoGenerated) append(".auto")
                append(".vtt")
            }
            File(dir, fileName).writeText(vtt)
            val entries = readIndex(dir).filterNot { it.optString(KEY_FILE) == fileName } +
                JSONObject()
                    .put(KEY_LANGUAGE, track.languageCode)
                    .put(KEY_NAME, track.name)
                    .put(KEY_AUTO, track.isAutoGenerated)
                    .put(KEY_FILE, fileName)
            File(dir, INDEX).writeText(JSONArray(entries).toString())
        } catch (e: Exception) {
            KLog.w(TAG, "Could not save ${track.languageCode} captions for $videoId: ${e.message}")
        }
    }

    /** The tracks saved for [videoId], authored ones first, as the online list orders them. */
    fun tracks(videoId: String): List<CaptionTrack> {
        val dir = folder(videoId)
        if (!dir.isDirectory) return emptyList()
        return try {
            readIndex(dir).mapNotNull { entry ->
                val file = File(dir, entry.optString(KEY_FILE))
                if (!file.isFile) return@mapNotNull null
                val language = entry.optString(KEY_LANGUAGE).takeIf { it.isNotBlank() }
                    ?: return@mapNotNull null
                CaptionTrack(
                    languageCode = language,
                    name = entry.optString(KEY_NAME).takeIf { it.isNotBlank() } ?: language,
                    baseUrl = file.toURI().toString(),
                    isAutoGenerated = entry.optBoolean(KEY_AUTO, false),
                )
            }.sortedBy { it.isAutoGenerated }
        } catch (e: Exception) {
            KLog.w(TAG, "Could not read saved captions for $videoId: ${e.message}")
            emptyList()
        }
    }

    /**
     * The cues of a saved track, or null when [track] is not one of this
     * store's - the caller then fetches it from YouTube as it always did.
     */
    fun cues(track: CaptionTrack): List<VttCue>? {
        if (!track.baseUrl.startsWith(FILE_SCHEME)) return null
        return try {
            val file = File(java.net.URI(track.baseUrl))
            // Never follow a file address out of this store's own folder.
            if (!file.canonicalPath.startsWith(root.canonicalPath + File.separator)) {
                return emptyList()
            }
            WebVttParser.parse(file.readText())
        } catch (e: Exception) {
            KLog.w(TAG, "Could not read saved ${track.languageCode} captions: ${e.message}")
            emptyList()
        }
    }

    /** Drop everything saved for [videoId], with the download it belonged to. */
    fun delete(videoId: String) {
        runCatching { folder(videoId).deleteRecursively() }
    }

    private fun readIndex(dir: File): List<JSONObject> {
        val index = File(dir, INDEX)
        if (!index.isFile) return emptyList()
        val array = JSONArray(index.readText())
        return (0 until array.length()).mapNotNull { array.optJSONObject(it) }
    }

    companion object {
        private const val TAG = "DownloadedCaptions"
        private const val DIRECTORY = "video_captions"
        private const val INDEX = "index.json"
        private const val FILE_SCHEME = "file:"
        private const val KEY_LANGUAGE = "language"
        private const val KEY_NAME = "name"
        private const val KEY_AUTO = "auto"
        private const val KEY_FILE = "file"
        private val UNSAFE = Regex("[^A-Za-z0-9_-]")

        /**
         * Most videos list a handful of tracks and all of them are kept. A few
         * list a hundred or more translations, and fetching every one would add
         * a hundred requests to a download for files nobody will open.
         */
        const val MAX_TRACKS_PER_VIDEO = 12

        /**
         * Which of [available] to keep when there are more than
         * [MAX_TRACKS_PER_VIDEO]: the language the captions menu was last left
         * on, the phone's languages, English, and the auto-generated track
         * (which is the language actually spoken), then the rest in the order
         * YouTube lists them until the limit. Pure, so the JVM suite can hold it.
         */
        fun tracksToKeep(
            available: List<CaptionTrack>,
            savedLanguage: String?,
            deviceLanguages: List<String>,
        ): List<CaptionTrack> {
            if (available.size <= MAX_TRACKS_PER_VIDEO) return available
            fun base(code: String) = code.substringBefore('-').lowercase(Locale.ROOT)
            val wanted = buildList {
                savedLanguage?.let { add(base(it)) }
                deviceLanguages.forEach { add(base(it)) }
                add("en")
            }.distinct()
            val picked = LinkedHashSet<CaptionTrack>()
            wanted.forEach { language ->
                available.filterTo(picked) { base(it.languageCode) == language }
            }
            available.filterTo(picked) { it.isAutoGenerated }
            for (track in available) {
                if (picked.size >= MAX_TRACKS_PER_VIDEO) break
                picked += track
            }
            return picked.take(MAX_TRACKS_PER_VIDEO)
        }
    }
}
