name: Telegram Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        run: echo 'Telegram Notification: A push has been made to main!'